apiVersion: gateway.networking.k8s.io/v1alpha2 # Check your cluster's supported API version (v1alpha2, v1beta1, or v1)
kind: TLSRoute
metadata:
  name: vault-tlsroute
  namespace: vault
spec:
  parentRefs:
  - name: eg  
    namespace: networking
    sectionName: vault-tls
  hostnames:
  - "vault.lab.mpopov.net"
  rules:
  - backendRefs:
    - name: vault-ui
      port: 8200