namespace: trino
route:
  enabled: true
  name: trino-httproute
  hostname: trino.lab.mpopov.net
  serviceName: trino
  servicePort: 8080
  gateway:
    name: eg
    namespace: networking
    sectionName: https
