{{- range .Values.clusters }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .namespace | quote }}
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ .name | quote }}
  namespace: {{ .namespace | quote }}
spec:
  instances: {{ $.Values.instances }}
  storage:
    size: {{ $.Values.storage.size | quote }}
  bootstrap:
    initdb:
      database: {{ .database | quote }}
      owner: {{ .owner | quote }}
      secret:
        name: {{ .secretName | quote }}
{{- end }}
