apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudnativepg
  namespace: argocd # must be where Argo CD is installed
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  sources:
    - repoURL: https://cloudnative-pg.github.io/charts
      targetRevision: v0.28.0
      chart: cloudnative-pg
      helm:
        values: |
          {{- toYaml .Values.cloudnativepg | nindent 10 }}

    - repoURL: https://github.com/mpopov678/test-cluster.git
      path: apps/cloudnativepg
      targetRevision: HEAD
      helm:
        values: |
          {{- toYaml .Values.cloudnativepgConfigs | nindent 10 }}

  destination:
    server: https://kubernetes.default.svc
    namespace: cnpg-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true