apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: delta-sharing
  namespace: argocd # must be where Argo CD is installed
  annotations:
    argocd.argoproj.io/sync-wave: "26"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/mpopov678/test-cluster.git
    path: apps/delta-sharing
    targetRevision: HEAD
    helm:
      values: |
        {{- toYaml .Values.deltaSharing | nindent 8 }}

  destination:
    server: https://kubernetes.default.svc
    namespace: delta-sharing
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
