apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd # must be where Argo CD is installed
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  sources:
    - repoURL: https://kubernetes-sigs.github.io/external-dns/
      targetRevision: v1.21.1
      chart: external-dns
      helm:
        values: |
          {{- toYaml .Values.externalDns | nindent 10 }}

    - repoURL: https://github.com/mpopov678/test-cluster.git
      path: apps/external-dns
      targetRevision: HEAD
      helm:
        values: |
          {{- toYaml .Values.externalDnsConfigs | nindent 10 }}

  destination:
    server: https://kubernetes.default.svc
    namespace: external-dns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true