apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prom
  namespace: argocd # must be where Argo CD is installed
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      targetRevision: v84.5.0
      chart: kube-prometheus-stack
      helm:
        values: |
          {{- toYaml .Values.kubePrometheus | nindent 10 }}

    - repoURL: https://github.com/mpopov678/test-cluster.git
      path: apps/kube-prom
      targetRevision: HEAD
      helm:
        values: |
          {{- toYaml .Values.kubePrometheusConfigs | nindent 10 }}

  destination:
    server: https://kubernetes.default.svc
    namespace: kube-prom
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true