apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lakehouse-storage
  namespace: argocd # must be where Argo CD is installed
  annotations:
    argocd.argoproj.io/sync-wave: "21"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/mpopov678/test-cluster.git
    path: apps/lakehouse-storage
    targetRevision: HEAD
    helm:
      values: |
        {{- toYaml .Values.lakehouseStorage | nindent 8 }}

  destination:
    server: https://kubernetes.default.svc
    namespace: lakehouse
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
