apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: superset
  namespace: argocd # must be where Argo CD is installed
  annotations:
    argocd.argoproj.io/sync-wave: "28"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://apache.github.io/superset
      targetRevision: 0.15.5
      chart: superset
      helm:
        releaseName: superset
        values: |
          {{- toYaml .Values.superset | nindent 10 }}

    - repoURL: https://github.com/mpopov678/test-cluster.git
      path: apps/superset
      targetRevision: HEAD
      helm:
        values: |
          {{- toYaml .Values.supersetConfigs | nindent 10 }}

  destination:
    server: https://kubernetes.default.svc
    namespace: superset
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
