apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trino
  namespace: argocd # must be where Argo CD is installed
  annotations:
    argocd.argoproj.io/sync-wave: "27"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://trinodb.github.io/charts
      targetRevision: 1.42.2
      chart: trino
      helm:
        releaseName: trino
        values: |
          {{- toYaml .Values.trino | nindent 10 }}

    - repoURL: https://github.com/mpopov678/test-cluster.git
      path: apps/trino
      targetRevision: HEAD
      helm:
        values: |
          {{- toYaml .Values.trinoConfigs | nindent 10 }}

  destination:
    server: https://kubernetes.default.svc
    namespace: trino
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
