apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: valkey
  namespace: argocd # must be where Argo CD is installed
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  sources:
    - repoURL: https://valkey.io/valkey-helm/
      targetRevision: v0.9.4
      chart: valkey
      helm:
        values: |
          {{- toYaml .Values.valkey | nindent 10 }}

    - repoURL: https://github.com/mpopov678/test-cluster.git
      path: apps/valkey
      targetRevision: HEAD
      helm:
        values: |
          {{- toYaml .Values.valkeyConfigs | nindent 10 }}

  destination:
    server: https://kubernetes.default.svc
    namespace: valkey
  syncPolicy:
    automated:
      prune: true
      selfheal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true