apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: velero
  namespace: argocd # must be where Argo CD is installed
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  sources:
    - repoURL: https://vmware-tanzu.github.io/helm-charts/
      targetRevision: v12.0.1
      chart: velero
      helm:
        values: |
          {{- toYaml .Values.velero | nindent 10 }}

    - repoURL: https://github.com/mpopov678/test-cluster.git
      path: apps/velero
      targetRevision: HEAD
      helm:
        values: |
          {{- toYaml .Values.veleroConfigs | nindent 10 }}

  destination:
    server: https://kubernetes.default.svc
    namespace: velero
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true