namespace: iceberg
route:
  enabled: true
  name: iceberg-catalog-httproute
  hostname: iceberg-catalog.lab.mpopov.net
  serviceName: iceberg-catalog
  servicePort: 19120
  gateway:
    name: eg
    namespace: networking
    sectionName: https
