apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudnative-pg
  namespace: argocd # always argocd, do not change
spec:
  project: default
  source:
    repoURL: https://github.com/mpopov678/test-cluster.git
    targetRevision: main
    path: infra/cloudnativepg
  destination:
    server: https://kubernetes.default.svc
    namespace: cnpg-system
  syncPolicy:
    automated:
      prune: true
      enabled: true
    syncOptions:
      - CreateNamespace=true