apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd   # must be where Argo CD is installed
spec:
  project: default
  source:
    repoURL: https://charts.jetstack.io
    targetRevision: v1.20.2
    helm:
      values: |-
        config:
          enableGatewayAPI: true
        installCRDs: true
        dns01RecursiveNameservers: "8.8.8.8:53"
        dns01RecursiveNameserversOnly: true
    chart: cert-manager
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      enabled: true
    syncOptions:
      - CreateNamespace=true