# https://github.com/cilium/cilium/tree/main/install/kubernetes/cilium/templates
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cilium-agent-servicemonitor
  namespace: monitoring
  labels:
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: cilium-agent
  namespaceSelector:
    matchNames:
    - kube-system
  endpoints:
  - port: metrics
    interval: 10s
    honorLabels: true
    path: /metrics
  targetLabels:
  - k8s-app
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
  name: cilium-operator-servicemonitor
  namespace: monitoring
spec:
  endpoints:
  - honorLabels: true
    interval: 10s # scrape ever 10 seconds
    path: /metrics
    port: metrics
  namespaceSelector:
    matchNames:
    - kube-system
  selector:
    matchLabels:
      io.cilium/app: operator
      name: cilium-operator
  targetLabels:
  - io.cilium/app # label to copy onto metrics
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cilium-envoy-servicemonitor
  namespace: monitoring
  labels:
  annotations:
spec:
  selector:
    matchLabels:
      k8s-app: cilium-envoy
  namespaceSelector:
    matchNames:
    - monitoring
  endpoints:
  - port: envoy-metrics
    interval: 10s
    honorLabels: true
    path: /metrics
  targetLabels:
  - k8s-app