instances: 1
storage:
  size: 10Gi
clusters:
  - name: nessie-db
    namespace: iceberg
    database: nessie
    owner: nessie
    secretName: nessie-db-app
  - name: superset-db
    namespace: superset
    database: superset
    owner: superset
    secretName: superset-db-app
