name: spark-history-server
namespace: spark
namespaceLabels:
  spark-operator: enabled
image:
  repository: apache/spark
  tag: 4.1.2
  pullPolicy: IfNotPresent
replicaCount: 1
service:
  port: 18080
spark:
  eventLogDirectory: s3a://spark-events/
s3:
  endpoint: http://rustfs-svc.rustfs.svc.cluster.local:9000
  pathStyleAccess: "true"
  sslEnabled: "false"
  secretName: lakehouse-s3
resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: "1"
    memory: 1Gi

hadoopAws:
  enabled: true
  downloaderImage: busybox:1.36
  jars:
    - https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-aws/3.4.1/hadoop-aws-3.4.1.jar
    - https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-bundle/1.12.720/aws-java-sdk-bundle-1.12.720.jar
route:
  enabled: true
  name: spark-history-httproute
  hostname: spark-history.lab.mpopov.net
  gateway:
    name: eg
    namespace: networking
    sectionName: https
