# global value that can be used in all subcharts
global:
  domain: "lab.mpopov.net"

certManager:
  config:
    enableGatewayAPI: true
  installCRDs: true
  dns01RecursiveNameservers: "8.8.8.8:53"
  dns01RecursiveNameserversOnly: true

certManagerConfigs:
  acmeServer: "https://acme-staging-v02.api.letsencrypt.org/directory"

longhorn:
  defaultSettings:
    defaultDataPath: "/var/mnt/longhorn"
  preUpgradeChecker:    
    jobEnabled: false
  persistence:
    defaultClass: false

longhornConfigs:

kubePrometheus:
  prometheus:
    prometheusSpec:
      storageSpec: 
        volumeClaimTemplate:
          spec:
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 20Gi
      serviceMonitorSelectorNilUsesHelmValues: false
      podMonitorSelectorNilUsesHelmValues: false
  grafana:
    persistence:
      enabled: true
      type: sts
      accessModes:
        - ReadWriteOnce
      size: 20Gi
      finalizers:
        - kubernetes.io/pvc-protection
    adminUser: admin
    adminPassword: admin

kubePrometheusConfigs:

vault:
  # Vault Helm chart Value Overrides
  global:
    enabled: true
    tlsDisable: false
    resources:
      requests:
        memory: 256Mi
        cpu: 250m
      limits:
        memory: 256Mi
        cpu: 250m

  server:
    # Use the Enterprise Image
    image:
      repository: "hashicorp/vault"
      tag: "1.16.1"

    # These Resource Limits are in line with node requirements in the
    # Vault Reference Architecture for a Small Cluster
    resources:
      requests:
        memory: 8Gi
        cpu: 2000m
      limits:
        memory: 16Gi
        cpu: 2000m

    # For HA configuration and because we need to manually init the vault,
    # we need to define custom readiness/liveness Probe settings
    readinessProbe:
      enabled: true
      path: "/v1/sys/health?standbyok=true&sealedcode=204&uninitcode=204"
    livenessProbe:
      enabled: true
      path: "/v1/sys/health?standbyok=true"
      initialDelaySeconds: 60

    # extraEnvironmentVars is a list of extra environment variables to set with the stateful set. These could be
    # used to include variables required for auto-unseal.

    # COMMENTED BECAUSE USING TRUSTED CERTS
    extraEnvironmentVars:
      VAULT_CACERT: /vault/userconfig/root-secret/ca.crt

    # extraVolumes is a list of extra volumes to mount. These will be exposed
    # to Vault in the path `/vault/userconfig/<name>/`.

    extraVolumes:
      - type: secret
        name: root-secret
    # COMMENTED BECAUSE USING TRUSTED CERTS
      # - type: secret
      #   name: tls-server
      # - type: secret
      #   name: tls-ca
      # - type: secret
      #   name: kms-creds

    # This configures the Vault Statefulset to create a PVC for audit logs.
    # See https://www.vaultproject.io/docs/audit/index.html to know more
    dataStorage:
      enabled: true
    auditStorage:
      enabled: true

    standalone:
      enabled: false

    # Run Vault in "HA" mode.
    ha:
      enabled: true
      replicas: 1
      raft:
        enabled: true
        setNodeId: true

        config: |
          ui = true
          cluster_name = "vault-integrated-storage"
          listener "tcp" {
            address = "[::]:8200"
            cluster_address = "[::]:8201"
            tls_cert_file = "/vault/userconfig/root-secret/tls.crt"
            tls_key_file = "/vault/userconfig/root-secret/tls.key"
          }

          storage "raft" {
            path = "/vault/data"
            retry_join {
              leader_api_addr = "https://vault-0.vault-internal:8200"
              leader_ca_cert_file = "/vault/userconfig/root-secret/ca.crt"
              leader_client_cert_file = "/vault/userconfig/root-secret/tls.crt"
              leader_client_key_file = "/vault/userconfig/root-secret/tls.key"
            }
          } 
        # COMMENTED BECAUSE USING 1 REPLICA
        # retry_join {
        #   leader_api_addr = "https://vault-1.vault-internal:8200"
        #   leader_ca_cert_file = "/vault/userconfig/tls-ca/ca.crt"
        #   leader_client_cert_file = "/vault/userconfig/vault-tls/tls.crt"
        #   leader_client_key_file = "/vault/userconfig/vault-tls/tls.key"
        # }
        # retry_join {
        #   leader_api_addr = "https://vault-2.vault-internal:8200"
        #   leader_ca_cert_file = "/vault/userconfig/tls-ca/ca.crt"
        #   leader_client_cert_file = "/vault/userconfig/vault-tls/tls.crt"
        #   leader_client_key_file = "/vault/userconfig/vault-tls/tls.key"
        # }
        # retry_join {
        #   leader_api_addr = "https://vault-3.vault-internal:8200"
        #   leader_ca_cert_file = "/vault/userconfig/tls-ca/ca.crt"
        #   leader_client_cert_file = "/vault/userconfig/vault-tls/tls.crt"
        #   leader_client_key_file = "/vault/userconfig/vault-tls/tls.key"
        # }
        # retry_join {
        #   leader_api_addr = "https://vault-4.vault-internal:8200"
        #   leader_ca_cert_file = "/vault/userconfig/tls-ca/ca.crt"
        #   leader_client_cert_file = "/vault/userconfig/vault-tls/tls.crt"
        #   leader_client_key_file = "/vault/userconfig/vault-tls/tls.key"
        # }

  # Vault UI
  ui:
    enabled: true
    serviceType: "ClusterIP"
    serviceNodePort: null
    externalPort: 8200


vaultConfigs:


valkey:
  dataStorage:
    enabled: true
    requestedSize: 10Gi


valkeyConfigs:


cloudnativepg:


cloudnativepgConfigs:


harbor:
  expose:
    type: clusterIP
    tls:
      enabled: false # handled by GatewayAPI

  persistence:
    enabled: true
    resourcePolicy: "" # set keep to avoid deleting PVCs after helm delete
    persistentVolumeClaim:
      registry:
        accessMode: ReadWriteOnce
        size: 5Gi
      jobservice:
        jobLog:
          accessMode: ReadWriteOnce
          size: 1Gi
      trivy:
        accessMode: ReadWriteOnce
        size: 5Gi

  harborAdminPassword: "Harbor12345"

  database:
    type: external
    external:
      host: "postgres-cluster-rw.harbor.svc.cluster.local" # static hostname
      port: "5432" 
      username: "app" # found in postgres cluster secret
      password: "" # automatically extracted from secret
      coreDatabase: "app" # found in postgres cluster secret
      existingSecret: "postgres-cluster-app"
      sslmode: "require" # postgres enforces SASL

  redis:
    type: external
    external:
      addr: "valkey.valkey.svc.cluster.local:6379" # static hostname


harborConfigs: