# global value that can be used in all subcharts
global:
  domain: "lab.mpopov.net"

certManager:
  config:
    enableGatewayAPI: true
  installCRDs: true
  dns01RecursiveNameservers: "8.8.8.8:53"
  dns01RecursiveNameserversOnly: true

certManagerConfigs:
  acmeServer: "https://acme-staging-v02.api.letsencrypt.org/directory"

longhorn:
  defaultSettings:
    defaultDataPath: "/var/mnt/longhorn"
  preUpgradeChecker:    
    jobEnabled: false
  persistence:
    defaultClass: false