apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: networking
  namespace: argocd # must be where Argo CD is installed
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/mpopov678/test-cluster.git
    path: testchart/templates/networking
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: networking
  syncPolicy:
    automated:
      prune: true
      selfheal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true