apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Pull the base installation manifests from the stable branch
resources:
  - github.com/argoproj/argo-cd//manifests/cluster-install?ref=stable
  - test.yaml
# Patch the argocd-cmd-params-cm ConfigMap to include the insecure flag
patches:
  - target:
      kind: ConfigMap
      name: argocd-cmd-params-cm
    patch: |-
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: argocd-cmd-params-cm
      data:
        server.insecure: "true"
