apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vault
helmCharts:
  - name: vault
    repo: https://helm.releases.hashicorp.com
    version: v0.28.0
    releaseName: vault
    includeCRDs: true
    valuesFile: values.yaml
    # valuesInline:

resources:
- certificate.yaml
- tlsroute.yaml